### PR TITLE
Fix a panic that could occur when `context` was omitted

### LINKED ISSUE #78: Panic building image with inline Dockerfile
### What happened?

When building a dockerBuild.Image with an inline Dockerfile, I get the following panic:

```text
Diagnostics:
  docker-build:index:Image (alpine):
    warning: No exports were specified so the build will only remain in the local build cache. Use `push` to upload the image to a registry, or silence this warning with a `cacheonly` export.
    error: Preview failed: error reading from server: EOF

  pulumi:pulumi:Stack (snyk-docker-build-dev):
    error: preview failed

    panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x2 addr=0x10 pc=0x104a53bc0]
    goroutine 97 [running]:
    github.com/pulumi/pulumi-docker-build/provider/internal.(*Image).Create(_, {_, _}, {_, _}, {{0x0, 0x0, 0x0}, 0x0, 0x140009f46d8, ...}, ...)
        /home/runner/work/pulumi-docker-build/pulumi-docker-build/provider/internal/image.go:708 +0x250
    github.com/pulumi/pulumi-go-provider/infer.(*derivedResourceController[...]).Create(0x105c46060?, {0x105c27660, 0x140009e07e0}, {{0x14000714000, 0x43}, 0x140009e04b0, 0x0, 0x1})
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-go-provider@v0.16.0/infer/resource.go:1026 +0x254
    github.com/pulumi/pulumi-go-provider/middleware/dispatch.Wrap.func6({0x105c27660, 0x140009e07e0}, {{0x14000714000, 0x43}, 0x140009e04b0, 0x0, 0x1})
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-go-provider@v0.16.0/middleware/dispatch/dispatch.go:90 +0x134
    github.com/pulumi/pulumi-go-provider/middleware/context.Wrap.delegateIO[...].func9({{0x14000714000?, 0x43?}, 0x140009e04b0, 0x0, 0x1})
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-go-provider@v0.16.0/middleware/context/context.go:48 +0x7c
    github.com/pulumi/pulumi-go-provider/middleware/cancel.Wrap.setCancel2[...].func14({{0x14000714000?, 0x43?}, 0x140009e04b0, 0x0, 0x1})
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-go-provider@v0.16.0/middleware/cancel/cancel.go:133 +0xe8
    github.com/pulumi/pulumi-go-provider.(*provider).Create(0x14000cc83f0, {0x105c165b8?, 0x140009e0420}, 0x140009c8d20)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-go-provider@v0.16.0/provider.go:852 +0x1ac
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Create_Handler.func1({0x105c165b8, 0x140009e0420}, {0x10594c280?, 0x140009c8d20})
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.113.0/proto/go/provider_grpc.pb.go:593 +0x74
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1({0x105c165b8, 0x14000c0fb00}, {0x10594c280, 0x140009c8d20}, 0x14000c3c140, 0x140009f63d8)
        /home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x2e8
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Create_Handler({0x105ac1580?, 0x14000c36470}, {0x105c165b8, 0x14000c0fb00}, 0x1400066c500, 0x14000c34160)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.113.0/proto/go/provider_grpc.pb.go:595 +0x12c
    google.golang.org/grpc.(*Server).processUnaryRPC(0x14000ca0000, {0x105c165b8, 0x14000c0f9e0}, {0x105c2af60, 0x14000682820}, 0x14000232120, 0x14000c80ba0, 0x107638c00, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.62.1/server.go:1386 +0xba0
    google.golang.org/grpc.(*Server).handleStream(0x14000ca0000, {0x105c2af60, 0x14000682820}, 0x14000232120)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.62.1/server.go:1797 +0xc70
    google.golang.org/grpc.(*Server).serveStreams.func2.1()
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.62.1/server.go:1027 +0x8c
    created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 24
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.62.1/server.go:1038 +0x150
```

### Example

```typescript
import * as dockerBuild from "@pulumi/docker-build";

new dockerBuild.Image("alpine", {
  tags: ["docker.io/joshkodroff/snyk-policy-alipne"],
  buildOnPreview: true,
  push: false,
  dockerfile: {
    inline: "FROM alpine:latest"
  }
});
```

### Output of `pulumi about`

```text
CLI          
Version      3.116.1
Go Version   go1.22.3
Go Compiler  gc

Plugins
KIND      NAME          VERSION
resource  docker-build  0.0.2
language  nodejs        unknown

Host     
OS       darwin
Version  14.4.1
Arch     arm64

This project is written in nodejs: executable='/opt/homebrew/bin/node' version='v21.2.0'

Current Stack: jkodrofftest/snyk-docker-build/dev

Found no resources associated with dev

Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/josh-pulumi-corp
User           josh-pulumi-corp
Organizations  josh-pulumi-corp, pulumi-gitlab-demo2, jkodrofftest, aws-partnership, zephyr, get-started-iac-aws-20240509, pulumi
Token type     personal

Dependencies:
NAME                  VERSION
@pulumi/docker-build  0.0.2
@pulumi/pulumi        3.116.1
@types/node           18.19.33
typescript            5.4.5

Pulumi locates its logs in /var/folders/5m/4n1x3f8151s35wc80w06z5k80000gn/T/ by default
```

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by blampe**
I could have sworn the context property was required, but evidently it isn't and we weren't handling the case when it was missing.

This PR updates things to set a default location of the current directory if the context is absent. Some unit tests are also added.

Fixes #78.

### CODE REVIEW

File: provider/internal/image_test.go [hunk 1]
```diff
@@ -273,6 +273,48 @@ func TestImageLifecycle(t *testing.T) {
 				}
 			},
 		},
+		{
+			name: "context defaults to current directory (pulumi-docker-build#78)",
+			client: func(t *testing.T) Client {
+				ctrl := gomock.NewController(t)
```
Comment (t0yv0) [inline provider/internal/image_test.go:279]: Side question, recommend using this generally at Pulumi? https://github.com/uber-go/mock 

I'm not a big fan of mocking prior to working in Go but in some situations it is practical, and I'd love a library recommendation.

File: provider/cmd/pulumi-resource-docker-build/schema.json [hunk 2]
```diff
@@ -412,11 +412,11 @@
         },
         "url": {
           "type": "string",
-          "description": "The cache server URL to use for artifacts.\n\nDefaults to `$ACTIONS_RUNTIME_URL`, although a separate action like\n`crazy-max/ghaction-github-runtime` is recommended to expose this\nenvironment variable to your jobs.",
```
Comment (t0yv0) [inline provider/cmd/pulumi-resource-docker-build/schema.json:415]: Curious why is this changing.

File: provider/internal/image_test.go (hunk 1 above)
Comment (blampe) [reply provider/internal/image_test.go:279]: Definitely! It can be a life saver for larger interfaces. I initially introduced it in the service and it's [caught on](https://github.com/search?q=org%3Apulumi+%22go.uber.org%2Fmock%22&type=code) since then.

File: provider/cmd/pulumi-resource-docker-build/schema.json (hunk 2 above)
Comment (blampe) [reply provider/cmd/pulumi-resource-docker-build/schema.json]: Fixed in https://github.com/pulumi/pulumi-docker-build/pull/89#discussion_r1621018357

**Comment by blampe** [comment]
> Defaults are too interesting as there's many ways to do them. We have some facilities to instruct SDK to inject defaults and probably underlying Go framework has some as well, guessing you've considered them and preferred to handle the default implicitly in the provider code.

Yeah, these defaults are more nuanced because they (context, dockerfile) depend on each other.
 
> Would it be useful to retain some integration tests that do use context as before (in addition to now testing the "context not set" path?

Yes that's still most of them, only one example was updated to match Josh's repro.
